### PR TITLE
Add JVM support

### LINKED ISSUE #10: Could not resolve all files for configuration ':shared:jvmCompileClasspath'
Hello,

I'm having this problem:
```
Execution failed for task ':shared:compileKotlinJvm'.
> Could not resolve all files for configuration ':shared:jvmCompileClasspath'.
   > Could not resolve io.github.kuuuurt:multiplatform-paging:0.3.9.
     Required by:
         project :shared
      > No matching variant of io.github.kuuuurt:multiplatform-paging:0.3.9 was found. The consumer was configured to find an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but:
          - Variant 'commonMainMetadataElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'debugApiElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'debugRuntimeElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosArm64ApiElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosArm64MetadataElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosX64ApiElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'iosX64MetadataElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'metadataApiElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9:
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'common' and the consumer needed an API of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'releaseApiElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9 declares an API of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'
          - Variant 'releaseRuntimeElements-published' capability io.github.kuuuurt:multiplatform-paging:0.3.9 declares a runtime of a component:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```
Which makes sense because this lib is only available for `android()` and `ios()` and it works just fine. But now I want to add a server app `jvm()` and `multiplatformPaging` is a dependency from `commonMain`. 

I guess this is something this lib should provide, maybe a dummy target for situations like this (don't know if it is possible 😅 )

### PR DESCRIPTION
**Pull request by msfjarvis**
The AndroidX Paging APIs currently used in the Android source set are not Android specific and can be used on desktop directly. To facilitate this with minimal code duplication, I have created a new `jvmAndAndroidMain` directory to share code between JVM and Android targets and moved all current Android code to it.

I have tested this in a Compose for Desktop project, commits for which can be found [here](https://github.com/msfjarvis/compose-lobsters/commits/desktop-paging) if needed.

This PR also includes a fix to allow syncing and publishing the project when `sonatype.properties` does not exist.

Fixes #10

### CODE REVIEW

**Comment by msfjarvis** [comment]
@kuuuurt would you be able to take a look at this anytime soon?

**Comment by kuuuurt** [comment]
Thansk for this @msfjarvis. I'm quite confused though. Isn't paging an Android dependency?

**Comment by msfjarvis** [comment]
> Thansk for this @msfjarvis. I'm quite confused though. Isn't paging an Android dependency?

It's not! `paging-common` is actually built as a ~pura Java~ JVM library. See the difference in applied plugins for [paging-common](https://github.com/androidx/androidx/blob/0a733a1e7471bbc23e5d3d177423229f4e574e58/paging/paging-common/build.gradle#L21-L24) versus [paging-runtime](https://github.com/androidx/androidx/blob/0a733a1e7471bbc23e5d3d177423229f4e574e58/paging/paging-runtime/build.gradle#L21-L25).

**Comment by msfjarvis** [comment]
@kuuuurt is there anything you'd like for me to change in this PR for it to be ready?

**Comment by kuuuurt** [comment]
Sorry @msfjarvis. I haven't found much time to work on personal projects. Thanks for letting me know that these are JVM libraries. Since these are not Android specific, can we just do a `jvm()` instead of targeting both then merging in a `jvmAndAndroidMain`?

**Comment by msfjarvis** [comment]
@kuuuurt I've dropped the Android target, and renamed the source set to `jvmMain`. Additionally I've also tested that I'm able to add it as a dependency in my Android sources.

**Comment by kuuuurt** [comment]
Thanks @msfjarvis. This would be included in the next release 0.4.5

**Comment by kuuuurt** [comment]
@msfjarvis 0.4.5 should be released

**Comment by msfjarvis** [comment]
> @msfjarvis 0.4.5 should be released

I saw, thanks a lot!

**Comment by glureau** [comment]
Thanks for your work! Could we also include your extensions like this one? I feels like it's a really good starting point for newcomer to find those functions + a minimal documentation on Desktop(Jvm). I can open another ticket and maybe even try to contribute if you're ok.


```kotlin
@Composable
fun <T : Any> Flow<PagingData<T>>.collectAsLazyPagingItems(): LazyPagingItems<T> {
  val lazyPagingItems = remember(this) { LazyPagingItems(this) }

  LaunchedEffect(lazyPagingItems) { lazyPagingItems.collectPagingData() }
  LaunchedEffect(lazyPagingItems) { lazyPagingItems.collectLoadState() }

  return lazyPagingItems
}
```

**Comment by msfjarvis** [comment]
> Thanks for your work! Could we also include your extensions like this one? I feels like it's a really good starting point for newcomer to find those functions + a minimal documentation on Desktop(Jvm). I can open another ticket and maybe even try to contribute if you're ok.
> 
> ```kotlin
> @Composable
> fun <T : Any> Flow<PagingData<T>>.collectAsLazyPagingItems(): LazyPagingItems<T> {
>   val lazyPagingItems = remember(this) { LazyPagingItems(this) }
> 
>   LaunchedEffect(lazyPagingItems) { lazyPagingItems.collectPagingData() }
>   LaunchedEffect(lazyPagingItems) { lazyPagingItems.collectLoadState() }
> 
>   return lazyPagingItems
> }
> ```

Unfortunately `LazyPagingItems` belongs to the `androidx.paging:paging-compose` library, which is [published as an Android library](https://maven.google.com/web/index.html?q=paging-compose#androidx.paging:paging-compose:1.0.0-alpha14) rather than a JVM one. This prevents extensions like that to be compiled for desktop. For my own needs I ended up [copying the class](https://github.com/msfjarvis/compose-lobsters/commit/2fa682048a89) and removing its use of Android classes by hand, and I suspect that will have to be the case for everyone until proper Paging support is available for compose-desktop.

**Comment by glureau** [comment]
Thanks for the tip, will do the same!

**Pull request merged**
